[metadata]
encoding = "cp1251"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
"224:255" = -32 # а-я -> А-Я
184 = -16 # ё -> Ё

[maps.lowercast]
"65:90" = 32 # A-Z -> a-z
"192:223" = 32 # А-Я -> а-я
168 = 16 # Ё -> ё

[maps.simplify]
"129|150|151|154|163" = 117 # üûùÜú -> u
"152" = 121 # ÿ -> y
"164|165" = 110 # ñÑ -> n
"131|132|133|134|142|143|145|146|160" = 97 # âäàåÄÅæÆá -> a
"130|136|137|138|144" = 101 # éêëèÉ -> e
"139|140|141|161" = 105 # ïîìí -> i
"147|148|149|153|162" = 111 # ôöòÖó -> o
"128|135" = 99 # Çç -> c

[maps.uppercase]
"129" = 154 # ü -> Ü
"164" = 165 # ñ -> Ñ
"132" = 142 # ä -> Ä
"134" = 143 # å -> Å
"130" = 144 # é -> É
"148" = 153 # ö -> Ö
"135" = 128 # ç -> Ç
"145" = 146 # æ -> Æ

[maps.lowercase]
"154" = 129 # Ü -> ü
"165" = 164 # Ñ -> ñ
"142" = 132 # Ä -> ä
"143" = 134 # Å -> å
"144" = 130 # É -> é
"153" = 148 # Ö -> ö
"128" = 135 # Ç -> ç
"146" = 145 # Æ -> æ 

[maps.utf]
# Conversion from utf-8 to cp1251
# А-Я
"37072" = 192
"37328" = 193
"37584" = 194
"37840" = 195
"38096" = 196
"38352" = 197
"38608" = 198
"38864" = 199
"39120" = 200
"39376" = 201
"39632" = 202
"39888" = 203
"40144" = 204
"40400" = 205
"40656" = 206
"40912" = 207
"41168" = 208
"41424" = 209
"41680" = 210
"41936" = 211
"42192" = 212
"42448" = 213
"42704" = 214
"42960" = 215
"43216" = 216
"43472" = 217
"43728" = 218
"43984" = 219
"44240" = 220
"44496" = 221
"44752" = 222
"45008" = 223
# а-я
"45264" = 224
"45520" = 225
"45776" = 226
"46032" = 227
"46288" = 228
"46544" = 229
"46800" = 230
"47056" = 231
"47312" = 232
"47568" = 233
"47824" = 234
"48080" = 235
"48336" = 236
"48592" = 237
"48848" = 238
"49104" = 239
"32977" = 240
"33233" = 241
"33489" = 242
"33745" = 243
"34001" = 244
"34257" = 245
"34513" = 246
"34769" = 247
"35025" = 248
"35281" = 249
"35537" = 250
"35793" = 251
"36049" = 252
"36305" = 253
"36561" = 254
"36817" = 255
"33232" = 168 # Ё
"37329" = 184 # ё
"34000" = 170 # Є
"38097" = 186 # є
"34768" = 175 # Ї
"38865" = 191 # ї
"34512" = 178 # І
"38609" = 179 # і
"37074" = 165 # Ґ
"37330" = 180 # ґ
"36560" = 161 # Ў
"40657" = 162 # ў
