[metadata]
encoding = "cp850"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
129 = 25 # ü -> Ü
130 = 14 # é -> É
131 = 51 # â -> Â
132 = 10 # ä -> Ä
133 = 50 # à -> À
134 = 9 # å -> Å
135 = -7 # ç -> Ç
"136:138" = 74 # ê-è -> Ê-È
"139:140" = 77 # ï-î -> Ï-Î
141 = 81 # ì -> Ì
145 = 1 # æ -> Æ
147 = 79 # ô -> Ô
148 = 5 # ö -> Ö
149 = 78 # ò -> Ò
"150:151" = 84 # û-ù -> Û-Ù
155 = 2 # ø -> Ø
160 = 21 # á -> Á
161 = 53 # í -> Í
162 = 62 # ó -> Ó
163 = 70 # ú -> Ú
164 = 1 # ñ -> Ñ
198 = 1 # ã -> Ã
208 = 1 # ð -> Ð
213 = -140 # ı -> I
228 = 1 # õ -> Õ
231 = 1 # þ -> Þ
236 = 1 # ý -> Ý

[maps.lowercast]
"65:90" = 32 # A-Z -> a-z
128 = 7 # Ç -> ç
142 = -10 # Ä -> ä
143 = -9 # Å -> å
144 = -14 # É -> é
146 = -1 # Æ -> æ
153 = -5 # Ö -> ö
154 = -25 # Ü -> ü
157 = -2 # Ø -> ø
165 = -1 # Ñ -> ñ
181 = -21 # Á -> á
182 = -51 # Â -> â
183 = -50 # À -> à
199 = -1 # Ã -> ã
209 = -1 # Ð -> ð
"210:212" = -74 # Ê-È -> ê-è
214 = -53 # Í -> í
"215:216" = -75 # Î-Ï -> î-ï
222 = -81 # Ì -> ì
224 = -62 # Ó -> ó
226 = -79 # Ô -> ô
227 = -78 # Ò -> ò
229 = -1 # Õ -> õ
232 = -1 # Þ -> þ
233 = -70 # Ú -> ú
"234:235" = -84 # Û-Ù -> û-ù
237 = -1 # Ý -> ý

[maps.simplify]
"128|135" = 99 # Çç -> c
"129|150|151|154|163|230|233|234|235" = 117 # üûùÜúµÚÛÙ -> u
"130|136|137|138|144|210|211|212" = 101 # éêëèÉÊËÈ -> e
"131|132|133|134|142|143|160|166|181|182|183|198|199" = 97 # âäàåÄÅáªÁÂÀãÃ -> a
"139|140|141|161|213|214|215|216|222" = 105 # ïîìíıÍÎÏÌ -> i
"147|148|149|153|155|157|162|167|224|226|227|228|229" = 111 # ôöòÖøØóºÓÔÒõÕ -> o
"152|236|237" = 121 # ÿýÝ -> y
"159" = 102 # ƒ -> f
"164|165" = 110 # ñÑ -> n
"208|209" = 100 # ðÐ -> d

[maps.utf]
34755 = 128 # Ç
48323 = 129 # ü
43459 = 130 # é
41667 = 131 # â
42179 = 132 # ä
41155 = 133 # à
42435 = 134 # å
42947 = 135 # ç
43715 = 136 # ê
43971 = 137 # ë
43203 = 138 # è
44995 = 139 # ï
44739 = 140 # î
44227 = 141 # ì
33987 = 142 # Ä
34243 = 143 # Å
35267 = 144 # É
42691 = 145 # æ
34499 = 146 # Æ
46275 = 147 # ô
46787 = 148 # ö
45763 = 149 # ò
48067 = 150 # û
47555 = 151 # ù
49091 = 152 # ÿ
38595 = 153 # Ö
40131 = 154 # Ü
47299 = 155 # ø
39107 = 157 # Ø
37574 = 159 # ƒ
41411 = 160 # á
44483 = 161 # í
46019 = 162 # ó
47811 = 163 # ú
45507 = 164 # ñ
37315 = 165 # Ñ
43714 = 166 # ª
47810 = 167 # º
33219 = 181 # Á
33475 = 182 # Â
32963 = 183 # À
41923 = 198 # ã
33731 = 199 # Ã
45251 = 208 # ð
37059 = 209 # Ð
35523 = 210 # Ê
35779 = 211 # Ë
35011 = 212 # È
45508 = 213 # ı
36291 = 214 # Í
36547 = 215 # Î
36803 = 216 # Ï
36035 = 222 # Ì
37827 = 224 # Ó
40899 = 225 # ß
38083 = 226 # Ô
37571 = 227 # Ò
46531 = 228 # õ
38339 = 229 # Õ
46530 = 230 # µ
48835 = 231 # þ
40643 = 232 # Þ
39619 = 233 # Ú
39875 = 234 # Û
39363 = 235 # Ù
48579 = 236 # ý
40387 = 237 # Ý
