[metadata]
encoding = "cp866"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
"160:175" = -32 # а-п -> А-П
"224:239" = -80 # р-я -> Р-Я
# 241 = -1 # ё -> ё - don't capitalize, beacuse 240 is ≡ symbol
243 = -1 # є -> Є
245 = -1 # ї -> Ї
247 = -1 # ў -> Ў

[maps.lowercast]
"65:90" = 32 # A-Z -> a-z
"128:143" = 32 # А-П -> а-п
"144:159" = 80 # Р-Я -> р-я
# 240 = 1 # Ё -> ё
242 = 1 # Є -> є
244 = 1 # Ї -> ї
246 = 1 # Ў -> ў

[maps.simplify]
"128|160" = 97 # Аа -> a
"129|161" = 98 # Бб -> b
"130|162" = 118 # Вв -> v
"131|163" = 103 # Гг -> g
"132|164" = 100 # Дд -> d
"133|157|165|237" = 101 # ЕЭеэ -> e
"135|167" = 122 # Зз -> z
"136|137|168|169" = 105 # ИЙий -> i
"138|170" = 107 # Кк -> k
"139|171" = 108 # Лл -> l
"140|172" = 109 # Мм -> m
"141|173" = 110 # Нн -> n
"142|174" = 111 # Оо -> o
"143|175" = 112 # Пп -> p
"144|224" = 114 # Рр -> r
"145|225" = 115 # Сс -> s
"146|226" = 116 # Тт -> t
"147|227|246|247" = 117 # УуЎў -> u
"148|228" = 102 # Фф -> f
"155|235" = 121 # Ыы -> y

[maps.uppercase]

[maps.lowercase]

[maps.utf]
37072 = 128 # А
37328 = 129 # Б
37584 = 130 # В
37840 = 131 # Г
38096 = 132 # Д
38352 = 133 # Е
38608 = 134 # Ж
38864 = 135 # З
39120 = 136 # И
39376 = 137 # Й
39632 = 138 # К
39888 = 139 # Л
40144 = 140 # М
40400 = 141 # Н
40656 = 142 # О
40912 = 143 # П
41168 = 144 # Р
41424 = 145 # С
41680 = 146 # Т
41936 = 147 # У
42192 = 148 # Ф
42448 = 149 # Х
42704 = 150 # Ц
42960 = 151 # Ч
43216 = 152 # Ш
43472 = 153 # Щ
43728 = 154 # Ъ
43984 = 155 # Ы
44240 = 156 # Ь
44496 = 157 # Э
44752 = 158 # Ю
45008 = 159 # Я
45264 = 160 # а
45520 = 161 # б
45776 = 162 # в
46032 = 163 # г
46288 = 164 # д
46544 = 165 # е
46800 = 166 # ж
47056 = 167 # з
47312 = 168 # и
47568 = 169 # й
47824 = 170 # к
48080 = 171 # л
48336 = 172 # м
48592 = 173 # н
48848 = 174 # о
49104 = 175 # п
32977 = 224 # р
33233 = 225 # с
33489 = 226 # т
33745 = 227 # у
34001 = 228 # ф
34257 = 229 # х
34513 = 230 # ц
34769 = 231 # ч
35025 = 232 # ш
35281 = 233 # щ
35537 = 234 # ъ
35793 = 235 # ы
36049 = 236 # ь
36305 = 237 # э
36561 = 238 # ю
36817 = 239 # я
33232 = 240 # Ё
37329 = 241 # ё
34000 = 242 # Є
38097 = 243 # є
34768 = 244 # Ї
38865 = 245 # ї
36560 = 246 # Ў
40657 = 247 # ў
