[metadata]
encoding = "cp866u"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
"160:175" = -32 # а-п -> А-П
"224:239" = -80 # р-я -> Р-Я
# 241 = -1 # ё -> Ё
243 = -1 # ґ -> Ґ
245 = -1 # є -> Є
247 = -1 # і -> І
249 = -1 # ї -> Ї

[maps.lowercast]
"65:90" = 32 # A-Z -> a-z
"128:143" = 32 # А-П -> а-п
"144:159" = 80 # Р-Я -> р-я
# 240 = 1 # Ё -> ё
242 = 1 # Ґ -> ґ
244 = 1 # Є -> є
246 = 1 # І -> і
248 = 1 # Ї -> ї

[maps.simplify]
"129|150|151|154|163" = 117 # üûùÜú -> u
"152" = 121 # ÿ -> y
"164|165" = 110 # ñÑ -> n
"131|132|133|134|142|143|145|146|160" = 97 # âäàåÄÅæÆá -> a
"130|136|137|138|144" = 101 # éêëèÉ -> e
"139|140|141|161" = 105 # ïîìí -> i
"147|148|149|153|162" = 111 # ôöòÖó -> o
"128|135" = 99 # Çç -> c

[maps.utf]
37072 = 128 # А
37328 = 129 # Б
37584 = 130 # В
37840 = 131 # Г
38096 = 132 # Д
38352 = 133 # Е
38608 = 134 # Ж
38864 = 135 # З
39120 = 136 # И
39376 = 137 # Й
39632 = 138 # К
39888 = 139 # Л
40144 = 140 # М
40400 = 141 # Н
40656 = 142 # О
40912 = 143 # П
41168 = 144 # Р
41424 = 145 # С
41680 = 146 # Т
41936 = 147 # У
42192 = 148 # Ф
42448 = 149 # Х
42704 = 150 # Ц
42960 = 151 # Ч
43216 = 152 # Ш
43472 = 153 # Щ
43728 = 154 # Ъ
43984 = 155 # Ы
44240 = 156 # Ь
44496 = 157 # Э
44752 = 158 # Ю
45008 = 159 # Я
45264 = 160 # а
45520 = 161 # б
45776 = 162 # в
46032 = 163 # г
46288 = 164 # д
46544 = 165 # е
46800 = 166 # ж
47056 = 167 # з
47312 = 168 # и
47568 = 169 # й
47824 = 170 # к
48080 = 171 # л
48336 = 172 # м
48592 = 173 # н
48848 = 174 # о
49104 = 175 # п
32977 = 224 # р
33233 = 225 # с
33489 = 226 # т
33745 = 227 # у
34001 = 228 # ф
34257 = 229 # х
34513 = 230 # ц
34769 = 231 # ч
35025 = 232 # ш
35281 = 233 # щ
35537 = 234 # ъ
35793 = 235 # ы
36049 = 236 # ь
36305 = 237 # э
36561 = 238 # ю
36817 = 239 # я
33232 = 240 # Ё
37329 = 241 # ё
37074 = 242 # Ґ
37330 = 243 # ґ
34000 = 244 # Є
38097 = 245 # є
34512 = 246 # І
38609 = 247 # і
34768 = 248 # Ї
38865 = 249 # ї
