[metadata]
name = "dfint localization hook offsets"
version = "50.10 steam win64"
checksum = 0x6507BEAC

[offsets]
string_copy_n = 0xBAD0
string_append_n = 0xBC10
convert_ulong_to_string = 0x3C14E0
addst = 0x801230
addst_top = 0x801310
addst_flag = 0x800FA0
standardstringentry = 0x9070D0
simplify_string = 0x3C2010
upper_case_string = 0x3C2350
lower_case_string = 0x3C21B0
capitalize_string_words = 0x3C24F0
capitalize_string_first_word = 0x3C2770
