[metadata]
name = "dfint localization hook offsets"
version = "50.12 classic win64"
checksum = 0x65E841AF

[offsets]
string_copy_n = 0xD4E0
string_append_n = 0xD620
addst = 0x8139C0
addst_top = 0x813AA0
addst_flag = 0x8138D0
standardstringentry = 0x919C90
simplify_string = 0x3D3380
upper_case_string = 0x3D36C0
lower_case_string = 0x3D3520
capitalize_string_words = 0x3D3860
capitalize_string_first_word = 0x3D3AE0
