name: Update dictionary manifest
on:
  repository_dispatch:
    types: [dict]
  push:
    branches: [ main ]
    paths:
      - 'automation/dict_manifest_update.py'
      - 'store/encodings/*'
      - 'store/fonts/*'
      - 'metadata/dict.json'
      - '.github/workflows/update-dict-manifest.yml'

jobs:
  dict:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4.2.0
        with:
          version: "latest"

      - name: Run update script
        run: uv run automation/dict_manifest_update.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update dictionary manifest"
